---
slug: godot_book
filename: godot_book
title: Godot High Score Tables
subtitle: Change me
description: Change me.
author: Richard Smith
copyright: 2021
uuid: dda9e178-a6c4-4caa-94a9-c241ca2abbca
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
